all:
  hosts:
    nagios.servers.test-net.work:
      ansible_become: yes
      ansible_become_method: sudo
      ansible_user: ansible

  children:
    proxmoxvms:
      hosts:
        nagios.servers.test-net.work: