all:
  hosts:
    nagios.servers.test-net.work:
    jenkins.servers.test-net.work:
    sql.servers.test-net.work:
    pihole-2.servers.test-net.work:
    pihole-1.servers.test-net.work:
    docker.servers.test-net.work:
    plex.wireless.test-net.work:
    mediatools.servers.test-net.work:
    backuppi.servers.test-net.work:
    kube1.servers.test-net.work:
    kube2.servers.test-net.work:
    kube3.servers.test-net.work:
    kube4.servers.test-net.work:
    kube5.servers.test-net.work: